@extends('_layouts.master')

@section('pageID', 'terms')

@section('navbar-classes', 'navbar-light')

@section('pageTitle', 'Terms and conditions')

@section('body')

	<div class="container">

		<header class="pageHeader">
			<h1 class="pageHeader__heading">Terms and Conditions</h1>
		</header>

		<section class="section section--terms-overview">

		    <p class="section__heading">Overview</p>
		    <div class="section__content">
		            <p>These Terms and Conditions (“Conditions”) are the terms and conditions that regulate access to and use of the website that Internxt Universal Technologies SLU (“Internxt”), a company registered in Calle San Vicente Martir 85, 46007, Valencia, Spain, and with NIF [Spanish tax ID number] B98936354, puts at the disposal of its online users and clients. These Terms and Conditions shall be governed and construed under Spanish Law and shall be subject to the exclusive jurisdiction of the Courts of Valencia, Spain, should any dispute, claim or disagreement arise from them. Internxt may update and amend these Terms and Conditions at any time and without prior notice, to adapt them to current regulations and to technological or business changes. The User should frequently verify the Terms and Conditions to ensure they always have the most up-to-date version.</p>
		    </div>

		</section>

		<section class="section section--terms-website">

		    <p class="section__heading">Website</p>
		    <div class="section__content">
		        <p>Internxt's website includes internxt.com and all online Internxt sites (“Our Website”). Anyone visiting and browsing Our Website, actions that imply acceptance of these terms and conditions as well as our Privacy Police, is deemed a user (“User”). Should you not agree with any of these terms and conditions, we kindly ask you to stop using Our Website. Access to Our Website is free of charge unless a prior contract is required for access to specific contents or services, in which case users will be provided with clear information and asked for explicit acceptance of the service provision contract and corresponding payment. All the contents on Our Website, including, but not limited to, texts, diagrams, photos, graphics, logos, names, icons and computer applications, as well as domain names, are the property of Internxt (unless otherwise stated) or their rights or corresponding assignments have acquired and are protected under domestic and international legislation and regulations relating to intellectual property, domain- registration regulations and trademark-registration regulations. "Internxt" is a trademark registered with the European Trademarks Office.</p>

		        <p>Under no circumstances shall the User's access to Our Website or hiring of any Internxt' products be understood as implying a transfer, license or assignment, wholly or partly, of the above-mentioned rights from Internxt to the User. All trade names, logos, icons, slogans and distinctive signs on Our Website belong to Internxt or Internxt has received authorization from their owner for their use. Any use by the User that is unauthorized, for purposes other than those set forth in these Terms and Conditions of Our Website's contents and information or for commercial purposes as well as any infringement by the User of Internxt's Intellectual Property rights or trademarks, shall lead to the legally established liabilities and proceedings. Any information the User provides to Internxt shall be stored in a file that is the property of Internxt and registered with the Spanish Data-Protection Agency, processed in accordance with current legislation on personal data protection. For further information on our personal data collection and use policy, please consult our Privacy Policy. Internxt reserves the right to limit and/or interrupt access to Our Website, as well as the offerings and/or provision of any of the services and products it publishes at any time and without prior notice, for reasons of maintenance, security, power failure, technical and other issues, without that giving rise to any liability on its part or the right to request any financial compensation.</p>

		        <p>Internxt shall not be held liable,directly or indirectly, for any direct or indirect damage or loss of earnings resulting from website or Internxt services being unavailable. Internxt may include links to third parties and/or external websites, outside Internxt' control. Although we shall periodically check the legality, truthfulness, and relevance of these sites, we cannot guarantee their quality. Under such circumstances, Internxt cannot guarantee or assume any liability for such external contents or for any damage and/or loss that may result from accessing those sites. Internxt shall only be liable, under Article 17 of Spanish Law 34/2002, the Information Society Services and E-Commerce Act, of 11 July 2002, for contents which, on acquiring a reliable awareness of their illegality, fails to remove or disable their links. The user agrees to use the website in accordance with the applicable existing law, the general principles of morality and public order and, in any case, under the conditions set out in this website. It should also be emphasized that the user agrees to make appropriate use of services and contents of the website, avoiding the commission of unlawful acts which may constitute a crime or that may violate others’ rights or violate any regulation on the intellectual and industrial property. It is also forbidden to place on the website any content or information that may qualify as xenophobic, pornographic or might violate any human right. Finally, the inclusion or diffusion of virus, malware or illicit advertising through this website is also prohibited.</p>
		    </div>

		</section>

		<section class="section section--terms-">

		    <p class="section__heading">Service provision contract</p>
		    <div class="section__content">
		        <p>This Service Provision Contract (hereinafter, the “Contract”) defines the relations between Internxt and any natural or legal persons expressing their wish to hire the services governed by these terms and conditions through a request forwarded online to the Internxt website, internxt.com, (hereinafter, the “CLIENT”). By forwarding a request to the Internxt website for the hire of any of the products on offer, applicants become Internxt CLIENTS and are deemed to fully and expressly accept the terms and conditions of this Contract.</p>

		        <p>This acceptance authorizes Internxt to carry out the necessary payment-collection operations that enable CLIENTS to receive the services and products they have requested through the method of payment that they themselves have chosen in their request. Internxt reserves the right to unilaterally amend or replace the terms and conditions of the Contract, in which case CLIENTS will be notified of this by email ten days in advance. In addition to being on permanent display on the Internxt website, internxt.com, these documents may be requested by CLIENTS at any time, by sending an email to hello@internxt.com. The purpose of this Contract is to set forth the Terms and Conditions under which Internxt will provide the services hired by the CLIENT as well as the use of the services and the payments to be made by the CLIENT to Internxt for the same.</p>

		        <p>The services supplied to the CLIENT may be replaced or changed by Internxt at any time, provided that the CLIENT is given advance notice and equipment with features that are either similar to or better than the one originally hired. The CLIENT may not transfer or subrogate all or part of this Contract in favor of third parties without Internxt's accredited consent. Internxt may transfer this Contract to third parties without being required to notify the CLIENT of this in advance. Likewise, where Internxt deems it fit, it may subcontract part or all of the services it supplies to the CLIENT to third parties it considers sufficiently competent for such work without compromising the service it undertakes to provide to the CLIENT.</p>

		        <p>THE CLIENT ensures that all the information they provide through Internxt's website, for registration as a user and the hiring any of the services, is true and accurate. THE CLIENT likewise undertakes to amend any of the above-mentioned information, where necessary, so that Internxt is able to supply the services hired and receive its payments correctly. Once the service is in operation or the CLIENT receives confirmation of acceptance, the contract shall be deemed to have been accepted. Should Internxt, for any reason, turn down a request, it will notify the applicant of this, sending the reasons for its refusal to any of the addresses the applicant has stated in their request. The CLIENT shall choose the service with the features and duration that best meets their needs, which, under the terms and conditions set out herein, shall formalize the Contract between Internxt and the CLIENT. Internxt reserves the right to prevent certain IPs from gaining access to the CLIENT's server as well as any services that Internxt considers capable of temporarily or permanently compromising the security, integrity or correct functioning of the Internxt network.</p>

		        <p>Internxt shall be subject to the strict liability according to the provisions of these General Terms and Conditions of Hire and where it fails to provide the CLIENT with an adequate service, such liability shall be confined to refunding payments in proportion to the time elapsed during which the CLIENT did not receive a satisfactory service. Internxt reserves the right to interrupt the service in order to carry out any improvements, maintenance operations and/or restructuring measures that it deems necessary to ensure the best operation of the services it offers. Internxt undertakes, insofar as this is possible, to communicate to any such interruptions to the CLIENT as soon as it can and to do its utmost to ensure such interruptions are as brief as possible and cause minimum inconvenience to the CLIENT.</p>

		        <p>Internxt reserves the right to raise the prices of its services where the CLIENT has contracted a monthly- payment plan, giving forty-five (45) days' advance notice before it applies such a price rise. If the plan contracted by the CLIENT has a quarterly, six-monthly or annual payment period, Internxt shall be able to raise the price of its services as from the beginning of the following payment period, provided that at least forty five (45) days have elapsed since the notice of the price increase was given. Internxt shall not be liable for any unavailability of or malfunction in the hired service caused by the CLIENT's connection problems or by general problems on the Internet or by any acts of God or force majeure or as a result of any reasons that could not have been foreseen beyond Internxt' good faith or which arise from the CLIENT's own actions or from the CLIENT's inefficient or malicious usage. The CLIENT expressly waives any liability claim for any possible damage or harm caused by any negligence or fault on the CLIENT's part and that such liability shall, in any case, be confined to a refund of the proportional amount paid by the CLIENT for the period during which they had not received the service hired. It shall be the exclusive responsibility of each party to take out the corresponding insurance policies for indemnifying any possible liabilities that may arise from the General Terms and Conditions of Hire and their breach.</p>

		        <p>The CLIENT shall pay the amount for the services hired from Internxt corresponding to the service and plan contracted and which are displayed in detail on Internxt's website, internxt.com. These prices do not include the VAT that applies at any time or any other tax that may apply at any time and which shall be added to the total amount of the invoice for the service contracted. All services must be paid for in advance and Internxt shall not carry out any action relating to the provision of services until payment has been reliably confirmed. The service is understood to be monthly renewed unless an express statement to that effect. If the customer fails to pay, we will understand that the service will not be renewed and Internxt will cease its service, at any time the nonpayment may occur. If the client does not wish to continue with the service but the contract is still in force, he/she shall not be entitled to a refund of any amount. The CLIENT may request cancellation of the service cancellation at any such time they wish. The service will be canceled as soon as the last period contracted has expired unless the CLIENT expressly requests immediate cancellation. In neither case shall there be a refund of any of the amounts paid up to the cancellation date.</p>

		        <p>The CLIENT acknowledges that such a cancellation implies a complete and permanent deletion of all their data and information hosted by Internxt. The CLIENT may request a refund of the amount paid and the cancellation of the service, within a period of seven (7) days as from the hiring of the service, should they not be satisfied with the service for any reason. Provided that it confirms that reasonable use has been made of the service and that it is the first time that the refund has been requested, Internxt will then proceed to cancel the service and refund the amount paid by the CLIENT as soon as possible and in the form of payment, it deems appropriate. The refund will be free of charge for the CLIENT. Internxt shall be expressly exempt from any type of liability that may arise from any contents hosted by the CLIENT in the products contracted and the CLIENT shall accept liability for any civil, criminal or other types of proceedings. Internxt reserves the right to suspend or permanently cancel the service contracted by the CLIENT, should it reliably detect any form of activity that goes against the Law and to notify the corresponding authorities in that event and put all the CLIENT's information they require at the disposal of the court authorities.</p>

		        <p>The CLIENT is responsible for safekeeping the usernames and passwords they have created for accessing the administration area of the service hired in order to prevent any unauthorized third party from gaining access to these private areas. The services will be invoiced in advance, according to the invoicing cycle that is chosen by the CLIENT and which the latter will be able to choose when paying, under the options available to them at any time displayed on Internxt's website, internxt.com. The CLIENT will have access to their invoices in the repository they will find available to them on the user-Control Panel. When the CLIENT purchases any Internxt service, they accept that, once the contracted period has lapsed, the contract will automatically be renewed for the equivalent term and that Internxt might automatically charge for that period through the payment method that the CLIENT had chosen when hiring the service. The above notwithstanding, the CLIENT reserves the right to cancel the service at any time, as explained in Clause 6.3 in these terms and conditions. The Contract shall be deemed to be automatically renewed for equivalent terms provided that neither of the parties has given express notice, sufficiently in advance, of opposition to the renewal and, in any case, before the expiry of the initial term or of any of its extensions.</p>

		        <p>The Contract shall come into force as soon as the CLIENT accepts the General Terms and Conditions of Hire on Internxt's website, internxt.com, and shall remain in effect until the period chosen by the CLIENT on entering into the contract has expired. The Contract shall be deemed to be automatically renewed for equivalent terms provided that neither of the parties has given express notice, sufficiently in advance, of opposition to the renewal and, in any case, before the expiry of the initial term or of any of its extensions. These General Terms and Conditions of Hire shall cease to have effect for the reasons set out both in the Spanish Civil Code and in the Spanish Commercial Code and, more specifically, for the following reasons: (a) On the expiry of the contract term or any of its extensions; (b) by express mutual agreement between the parties in writing; and (c) by early termination of the General Terms and Conditions of Hire under the terms and conditions set forth in the following clause. In any event, the termination of the contractual relationship shall not exempt the parties from fulfilling their outstanding obligations.</p>

		        <p>The aforementioned capacity to terminate the contractual relationship notwithstanding, Internxt may withdraw or suspend its provision of services to the CLIENT at any time and without the need for prior notice, should it consider the CLIENT to have breached any of the obligations they have accepted under these General Terms and Conditions of Hire, and Internxt may require the CLIENT to pay for any damage and/or loss that may arise as a result of their breach. In accordance with prevailing laws and regulations on personal data protection, we notify you that your data will be entered in a processing system owned by Internxt Universal Technologies SLU, holding tax identification number A86125218 and having its registered office at Calle San Vicente Martir 85, 46007, Valencia, Spain, for the purposes of performance of the obligations under the agreement entered into between the parties.</p>

		        <p>In compliance with prevailing laws and regulations, Internxt gives notice that the data will be kept for the statutory period. By means of this clause, you are given notice that your data will be shared, if necessary, with government authorities and any entity with which the data must be shared for the purpose of providing the service referred to above. If the data are not shared with the entities referred to above, the services under this agreement cannot be provided. Internxt states that it will process the data legally, fairly, transparently, appropriately, relevantly, subject to limits, accurately and ensure that all data are up to date.</p>

		    	<p>Internxt, therefore, undertakes to take all reasonable steps for data to be erased or rectified without delay if they are inaccurate. In accordance with the rights conferred on you by prevailing laws and regulations on data protection, you may exercise your rights of access, rectification, limitation of processing, erasure, portability and objection to processing of your personal data, and surrounding the consent given to their processing, by writing to the postal address indicated above. You may approach the competent control authority to make any complaint you think fit. Finally, Internxt informs you that with your acquisition you give your express consent to the processing of the data referred to above in accordance with the current legislation. Following completion of the provision of the agreed services any personal data given by customers will be destroyed or returned by Internxt, if not longer needed. Internxt ensures the utmost confidentiality and privacy of the personal data using security measures that prevent any unauthorized change, loss, processing or access and therefore guarantees their integrity and security. Nevertheless, Internxt shall not be liable for any incidents that may affect the CLIENT's personal data, where these result from an unauthorised attack on or access to the systems in a way that proves impossible for it to detect or prevent, despite having adopted the necessary measures given the technology currently available, or which arise from negligence on the part of the CLIENT.</p>

    		</div>

		</section>

	</div>{{-- /.container --}}

@endsection
